import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/app/GlobalProvider/provider'
import Header from './Header'

const inter = Inter({
  subsets: ['cyrillic'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="ru" className={inter.className}>
      <body>
        <main className='box-border'> 
        {/* <main className='max-sm:max-h-screen h-screen box-border'>  */}
            <Header />
            <Provider>
                <div className='max-sm:px-5 max-sm:py-5 px-10 py-10 relative'>
                  {children}
                </div>
            </Provider>
        </main>
        </body>
    </html>
  )
}
